version: "3.8"

services:
  consul-server1:
    build: ./consul
    image: consul:local
    restart: always
    networks:
      - consul
    command: "consul agent -config-dir /etc/consul.d"
    container_name: consul-server1
    volumes:
      - ./consul/consul-server1.hcl:/etc/consul.d/consul-server1.hcl:ro
      - ./certs/:/etc/consul.d/certs/:ro
    ports:
      - "8300:8300"
      - "8301:8301"
      - "8301:8301/udp"
      - "8302:8302"
      - "8302:8302/udp"
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"

  consul-server2:
    build: ./consul
    image: consul:local
    restart: always
    networks:
      - consul
    command: "consul agent -config-dir /etc/consul.d"
    container_name: consul-server2
    volumes:
      - ./consul/consul-server2.hcl:/etc/consul.d/consul-server2.hcl:ro
      - ./certs/:/etc/consul.d/certs/:ro
    expose:
      - "8300"
      - "8301"
      - "8301/udp"
      - "8302"
      - "8302/udp"
      - "8500"
      - "8600/tcp"
      - "8600/udp"

  consul-server3:
    build: ./consul
    image: consul:local
    restart: always
    networks:
      - consul
    command: "consul agent -config-dir /etc/consul.d"
    container_name: consul-server3
    volumes:
      - ./consul/consul-server3.hcl:/etc/consul.d/consul-server3.hcl:ro
      - ./certs/:/etc/consul.d/certs/:ro
    expose:
      - "8300"
      - "8301"
      - "8301/udp"
      - "8302"
      - "8302/udp"
      - "8500"
      - "8600/tcp"
      - "8600/udp"
  
  vault-server1:
    build: ./vault
    image: vault:local
    restart: always
    container_name: vault-server1
    volumes:
      - ./vault/vault-server1.hcl:/etc/vault.d/vault-server1.hcl:ro
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    depends_on:
      - consul-server1
    networks:
      - consul
    command: "vault server -config=/etc/vault.d/vault-server1.hcl"

  vault-server2:
    build: ./vault
    image: vault:local
    restart: always
    container_name: vault-server2
    volumes:
      - ./vault/vault-server2.hcl:/etc/vault.d/vault-server2.hcl:ro
    expose:
      - "8200"
    cap_add:
      - IPC_LOCK
    depends_on:
      - consul-server1
    networks:
      - consul
    command: "vault server -config=/etc/vault.d/vault-server2.hcl"
  
networks:
  consul:
    name: consul
    driver: bridge
